--create database torgfirmaBradley
--drop database torgfirmaBradley
--use torgfirmabradley
--create table torgfirmabradley(id_postach int identity(1,1)not null primary key,
--nazva varchar(20) constraint nazva_format check (nazva like'[а-я]%'),
--index_p char(5) constraint ind_format check (index_p like'[0-9][0-9][0-9][0-9][0-9]')
--default 10000,
--addr varchar(50),
--city varchar(20) constraint city_format check (city like'м. [а-я]%'),
--region varchar(50),
--tel char(12) check (tel like'([0-9][0-9][0-9])[0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
----create table tovar
---- (id_tovar int IDENTITY(1,1) not null primary key,
---- Nazva_t varchar(20) constraint nazva_tf check (Nazva_t like '[А-я]%'),
---- Min_zap int check (Min_zap >0) default
----10, Zap_skl int, price money, 
---- post_prek smallint check (post_prek in (0,1)),
---- id_postach int not null foreign key (id_postach) references dbo.torgfirmaBradley(id_postach) 
----on delete cascade on update no action);
--create table klient
-- (id_klient int IDENTITY(1,1) not null primary key,
-- Nazva varchar(20) constraint nazvaformat check (Nazva like '[А-я]%'),
-- Index_p char(5) constraint intformat check (index_p like '[0-9][0-9][0-9][0-9][0-9]') 
--default 10000, Addr varchar(50),
-- City varchar(20) constraint cityformat check (City like 'м. [А-я]%'), 
--Region varchar(50),
-- tel char(12) check (tel like '([0-9][0-9][0-9])[0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
--Create table Sotrudnik(
--id_sotrudnik int identity(1,1) not null primary key,
--Fname varchar(20) constraint Fname__format check (Fname like '[А-Я]%') ,
--Name varchar(20) constraint name__format check (name like '[А-Я]%') ,
--Posada varchar(40) constraint posada__format check (posada like '[А-Я]%') ,
--Date_enter date,
--Date_birthday date,
--Index_p char(5) constraint ind__format check (index_p like '[0-9][0-9][0-9][0-9][0-9]') 
--default 10000, Adress varchar(50) ,
--City varchar(20) constraint city__format check (city like '[А-Я]%') , 
--Region varchar(20) constraint region__format check (region like '[А-Я]%') , 
--Country varchar(20) constraint country__format check (country like '[А-Я]%') , 
--Tel char (10) check (tel like '([0-9][0-9][0-9])[0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
--Foto varchar(50),
--Note text)
--Create table Zakaz(
--K_zakaz int identity(1, 1) primary key,
--K_klien int references [dbo].[klient](id_klient),
--K_sotrud int references [dbo].[Sotrudnik](id_sotrudnik),
--Date_rozm date default getdate(),
--Date_naznach date default getdate()+10)
--create table zakaz_tovar(
--id_zakaz int not null references zakaz(K_zakaz ) on update cascade on delete cascade, 
--id_tovar int not null references tovar(id_tovar) on update no action on delete cascade,
--kilk int check (kilk>0), znigka decimal (3,2) 
--primary key (id_zakaz, id_tovar))

--insert into [dbo].[torgfirmaBradley]([Nazva],[Index_p],[Addr],[City],[Region],[tel]) values
--('Миша','10001','Muhosranks 5','м. Мухина','Ukraine','(098)1234567'),
--('Доманк Торрето','10002','Indiya','м. Житомир','Ukraine','(098)6345287'),
--('Дима','10003','KIluko','м. Жало','Ukraine','(098)1562867')

--insert into [dbo].[tovar]([Nazva_t],[Min_zap],[Zap_skl],[price],[post_prek],[id_postach]) values
--('Ёршик','1337','1338','1336','0','5'),
--('Туалетная бумага','5','1000','3','1','6'),
--('Супер Енергетик','1000','1000000','1','0',(select id_postach from dbo.torgfirmaBradley where Nazva = 'Дима'))

--insert into [dbo].[klient]([Nazva],[Addr],[City],[Region],[tel]) values
--('Даня','Житомир 1336','м. Украина','Антартикика','(096)1564267'),
--('Миша','Житомир 1337','м. Украина','Антлоандита','(096)1634767'),
--('Влад','Житомир 1338','м. Украина','Хархув','(096)1264567')

--insert into [dbo].[Sotrudnik]([Fname],[Name],[Posada],[Date_enter],[Date_birthday],[Index_p],[Adress],[City],[Region],[Country],[Tel],[Foto],[Note]) values
--('Брудли','Даня','Генерал Инергетика','24.02.2111','06.10.1000','61252','Житомир','м. Европа','Альфацентавра','Луна','(981)1231567','имаж1.жпг','КРУТОЙ'),
--('Краснобокий','Мишка','Камандир Мопедов','12.08.2121','28.12.2007','61252','Житомир','м. Европа','Альфацентавра','Луна','(971)1637567','имаж2.жпг','Лысый'),
--('Фамилия','Владик','Инструктор','16.05.2021','06.05.2014','61252','Житомир','м. Европа','Альфацентавра','Луна','(911)1731667','имаж3.жпг','Маладец')


--insert into [dbo].[Zakaz] ([Date_rozm], [Date_naznach]) values 
--('6','4','2021/05/21', '2021/06/01'), 
--('7','5','2021/06/15', '2021/06/25'), 
--('8','6','2021/04/21', '2021/05/01');

--insert into [dbo].[zakaz_tovar]([id_zakaz],[id_tovar],[kilk],[znigka]) values 
--('1','1','1000','5.0'),
--('2','2','3001','2.5'),
--('3','3','1616','0.1');